name: Create Karate Report

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  karate:
    name: Test 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Karate tests
      run: mvn clean test

    - name: Test report
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: target/cucumber-html-reports/
        
